[package]
name = "hello2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib = { path = "../../packages/lib" }
rusqlite = { version = "0.30.0", features = ["bundled"] }
serde_json = "1.0"